export const sum=(rs,f)=>rs.reduce((n,r)=>n+(Number(f(r))||0),0);
export const mean=(rs,f)=>rs.length?sum(rs,f)/rs.length:null;
export const wilson=(w,n)=>{if(!n)return null;const z=1.96,p=w/n,d=1+z*z/n,c=(p+z*z/(2*n))/d,h=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/d;return [c-h,c+h];};
export function filterRows(rows,f={}){return rows.filter(r=>(!f.population||r.population===f.population)&&(!f.home||r.home===f.home)&&(!f.profile||r.profile===f.profile)&&(!f.reason||r.reason===f.reason)&&(!f.agents?.length||f.agents.every(a=>r.team.includes(a)))&&(!f.team||[...r.team].sort().join(',')===f.team)&&(!f.score||r.score>=+f.score)&&(!f.rank||r.rank<=+f.rank)&&(!f.turn||r.turn<=+f.turn)&&(!f.exactTurn||r.turn===+f.exactTurn)&&(!f.architect||(()=>{const a=r.suspects.find(t=>t.cell===3);return f.architect==='free'?!a?.arrested:f.architect==='own'?a?.by===r.home:a?.arrested&&a.by!==r.home;})())&&(!f.q||String(r.seed).includes(f.q.trim())));}
export function summary(rs){const n=rs.length,w=sum(rs,r=>r.victory);return {n,w,win:n?w/n:null,ci:wilson(w,n),individual:mean(rs,r=>r.victory?r.first:0),first:mean(rs,r=>r.first),score:mean(rs,r=>r.score),rank:mean(rs,r=>r.rank),turn:mean(rs,r=>r.turn),crisis:sum(rs,r=>r.reason==='crisis'),deadline:sum(rs,r=>r.reason==='deadline'),dead:mean(rs,r=>r.dead),captured:mean(rs,r=>r.captured)};}
export function groups(rs,key){const m=new Map();for(const r of rs){const k=key(r);if(!m.has(k))m.set(k,[]);m.get(k).push(r);}return [...m].map(([key,rows])=>({key,rows,...summary(rows)}));}
export function actionTotals(rs,agent=null){const out={};for(const r of rs){const sources=agent?r.agents.filter(a=>a.templateId===agent).map(a=>a.actions):[r.actions];for(const actions of sources)for(const [id,v] of Object.entries(actions||{})){const t=out[id]??={id,count:0,success:0,failed:0,stopped:0,rolls:0,chance:0,cost:0,fatigue:0,exposure:0,prestige:0};for(const k of Object.keys(t).filter(k=>k!=='id'))t[k]+=v[k]||0;}}return Object.values(out);}
export function csv(columns,rows){const cell=v=>{let t=v===null||v===undefined?'':String(v);if(typeof v==='string'&&/^[=+\-@]/.test(t))t="'"+t;return '"'+t.replaceAll('"','""')+'"';};return '\ufeff'+[columns.map(c=>cell(c.label)).join(';'),...rows.map(r=>columns.map(c=>cell(c.value(r))).join(';'))].join('\r\n');}
export function compareOnSeeds(selected,all){const seeds=new Set(selected.map(r=>r.seed));const sets=['v2','v3','mixed'].map(population=>({population,rows:all.filter(r=>r.population===population&&seeds.has(r.seed))}));return sets.map(s=>({...s,...summary(s.rows)}));}

// Compare all countries on exactly the same selected campaigns, including defeats.
export function countryComparisons(rows){const comparable=rows.filter(r=>r.finalScores);if(!comparable.length)return [];return Object.keys(comparable[0].finalScores).map(key=>{const rs=comparable.map(r=>{const values=Object.values(r.finalScores),max=Math.max(...values),score=r.finalScores[key],ties=values.filter(v=>Math.abs(v-max)<1e-8).length;return {...r,score,rank:1+values.filter(v=>v>score+1e-8).length,first:Math.abs(score-max)<1e-8?1/ties:0};});return {key,...summary(rs)};});}
